-- begin STARTUP_WALLET_TRADE_ACTION
alter table STARTUP_WALLET_TRADE_ACTION add constraint FK_STARTUP_WALLET_TRADE_ACTION_ON_WALLET foreign key (WALLET_ID) references STARTUP_WALLET(ID)^
create index IDX_STARTUP_WALLET_TRADE_ACTION_ON_WALLET on STARTUP_WALLET_TRADE_ACTION (WALLET_ID)^
-- end STARTUP_WALLET_TRADE_ACTION
